# --- Main Colors ---
background            #1a110e
foreground            #ffffff
cursor                #ffffff
cursor_text_color     #1a110e

selection_background  #e3baac
selection_foreground  #000000

url_color             #fff0b9

# --- ANSI Colors ---
color0                #1a110e
color1                #ffece9
color2                #fff0b9
color3                #ffece6
color4                #ffece6
color5                #d5c68e
color6                #e7bdb0
color7                #ffffff

color8                #53433e
color9                #ffaea4
color10               #d1c28a
color11               #e3baac
color12               #ffaf93
color13               #200b05
color14               #161100
color15               #ffffff

# --- Starship Prompt Bubbles ---
color255              #ffaf93
color254              #ffece6
color253              #e3baac
color252              #ffece6
color251              #d1c28a
color250              #fff0b9
color249              #ffaea4
color248              #ffece9

color232              #000000
color233              #000000
color234              #000000
color235              #000000
color236              #000000
color237              #000000
color238              #000000
color239              #000000
color240              #000000

# Matched with unthemed light/dark
color243              #ffece6
color244              #ffece9
color245              #d4beb7

# --- UI Elements ---
active_tab_foreground   #000000
active_tab_background   #ffece6
inactive_tab_foreground #000000
inactive_tab_background #ffaf93

active_border_color     #ffece6
inactive_border_color   #ffece6

# --- Marks ---
mark1_foreground        #000000
mark1_background        #ffdbcf
mark2_foreground        #000000
mark2_background        #ffdbcf
mark3_foreground        #000000
mark3_background        #f2e2a7
