# --- Main Colors ---
background            #18130b
foreground            #ffffff
cursor                #ffffff
cursor_text_color     #18130b

selection_background  #d8bf9d
selection_foreground  #000000

url_color             #e0f8ca

# --- ANSI Colors ---
color0                #18130b
color1                #ffece9
color2                #e0f8ca
color3                #ffedd9
color4                #ffedd9
color5                #b7cea2
color6                #dcc3a1
color7                #ffffff

color8                #4f4539
color9                #ffaea4
color10               #b3ca9f
color11               #d8bf9d
color12               #eeba6a
color13               #1b0f00
color14               #051500
color15               #ffffff

# --- Starship Prompt Bubbles ---
color255              #eeba6a
color254              #ffedd9
color253              #d8bf9d
color252              #ffedd9
color251              #b3ca9f
color250              #e0f8ca
color249              #ffaea4
color248              #ffece9

color232              #000000
color233              #000000
color234              #000000
color235              #000000
color236              #000000
color237              #000000
color238              #000000
color239              #000000
color240              #000000

# Matched with unthemed light/dark
color243              #ffedd9
color244              #ffece9
color245              #cfc0b0

# --- UI Elements ---
active_tab_foreground   #000000
active_tab_background   #ffedd9
inactive_tab_foreground #000000
inactive_tab_background #eeba6a

active_border_color     #ffedd9
inactive_border_color   #fdeedc

# --- Marks ---
mark1_foreground        #000000
mark1_background        #ffddb0
mark2_foreground        #000000
mark2_background        #fadebb
mark3_foreground        #000000
mark3_background        #d2eabd
