# --- Main Colors ---
background            #15130b
foreground            #ffffff
cursor                #ffffff
cursor_text_color     #15130b

selection_background  #cdc39e
selection_foreground  #000000

url_color             #d2fadc

# --- ANSI Colors ---
color0                #15130b
color1                #ffece9
color2                #d2fadc
color3                #fbf0c9
color4                #fff0b6
color5                #a9d0b4
color6                #d1c6a2
color7                #ffffff

color8                #4b4739
color9                #ffaea4
color10               #a5ccb0
color11               #cdc39e
color12               #d6c36b
color13               #151100
color14               #001509
color15               #ffffff

# --- Starship Prompt Bubbles ---
color255              #d6c36b
color254              #fff0b6
color253              #cdc39e
color252              #fbf0c9
color251              #a5ccb0
color250              #d2fadc
color249              #ffaea4
color248              #ffece9

color232              #000000
color233              #000000
color234              #000000
color235              #000000
color236              #000000
color237              #000000
color238              #000000
color239              #000000
color240              #000000

# Matched with unthemed light/dark
color243              #fff0b6
color244              #ffece9
color245              #c9c2b1

# --- UI Elements ---
active_tab_foreground   #000000
active_tab_background   #fff0b6
inactive_tab_foreground #000000
inactive_tab_background #d6c36b

active_border_color     #fff0b6
inactive_border_color   #f7efdd

# --- Marks ---
mark1_foreground        #000000
mark1_background        #f7e388
mark2_foreground        #000000
mark2_background        #ede2bc
mark3_foreground        #000000
mark3_background        #c4eccf
