
$background = rgba(15130bff)

$blue = rgba(f5edffff)

$blue_container = rgba(cab9faff)

$blue_source = rgba(0000ffff)

$blue_value = rgba(0000ffff)

$error = rgba(ffece9ff)

$error_container = rgba(ffaea4ff)

$green = rgba(e0faaaff)

$green_container = rgba(b3cc81ff)

$green_source = rgba(00ff00ff)

$green_value = rgba(00ff00ff)

$inverse_on_surface = rgba(000000ff)

$inverse_primary = rgba(544700ff)

$inverse_surface = rgba(e8e2d4ff)

$on_background = rgba(e8e2d4ff)

$on_blue = rgba(000000ff)

$on_blue_container = rgba(000000ff)

$on_error = rgba(000000ff)

$on_error_container = rgba(000000ff)

$on_green = rgba(000000ff)

$on_green_container = rgba(000000ff)

$on_primary = rgba(000000ff)

$on_primary_container = rgba(000000ff)

$on_primary_fixed = rgba(000000ff)

$on_primary_fixed_variant = rgba(151100ff)

$on_red = rgba(000000ff)

$on_red_container = rgba(000000ff)

$on_secondary = rgba(000000ff)

$on_secondary_container = rgba(000000ff)

$on_secondary_fixed = rgba(000000ff)

$on_secondary_fixed_variant = rgba(151100ff)

$on_surface = rgba(ffffffff)

$on_surface_variant = rgba(ffffffff)

$on_tertiary = rgba(000000ff)

$on_tertiary_container = rgba(000000ff)

$on_tertiary_fixed = rgba(000000ff)

$on_tertiary_fixed_variant = rgba(001509ff)

$outline = rgba(f7efddff)

$outline_variant = rgba(c9c2b1ff)

$primary = rgba(fff0b6ff)

$primary_container = rgba(d6c36bff)

$primary_fixed = rgba(f7e388ff)

$primary_fixed_dim = rgba(dac76fff)

$red = rgba(ffece5ff)

$red_container = rgba(ffb08dff)

$red_source = rgba(ff0000ff)

$red_value = rgba(ff0000ff)

$scrim = rgba(000000ff)

$secondary = rgba(fbf0c9ff)

$secondary_container = rgba(cdc39eff)

$secondary_fixed = rgba(ede2bcff)

$secondary_fixed_dim = rgba(d1c6a2ff)

$shadow = rgba(000000ff)

$source_color = rgba(c3b058ff)

$surface = rgba(15130bff)

$surface_bright = rgba(535046ff)

$surface_container = rgba(333027ff)

$surface_container_high = rgba(3e3b32ff)

$surface_container_highest = rgba(4a473dff)

$surface_container_low = rgba(222017ff)

$surface_container_lowest = rgba(000000ff)

$surface_dim = rgba(15130bff)

$surface_tint = rgba(dac76fff)

$surface_variant = rgba(4b4739ff)

$tertiary = rgba(d2fadcff)

$tertiary_container = rgba(a5ccb0ff)

$tertiary_fixed = rgba(c4eccfff)

$tertiary_fixed_dim = rgba(a9d0b4ff)
